imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }
    - { resource: "@OAuthServerBundle/Resources/config/services.yml" }
    - { resource: "@UserBundle/Resources/config/services.yml" }
#    - { resource: "@CodeReviewRestBundle/Resources/config/services.yml" }
    - { resource: "@ApiBundle/Resources/config/services.yml" }
    - { resource: "@FOSOAuthServerBundle/Resources/config/security.xml" }
    - { resource: fullsign.yml }
    
    

# Put parameters here that don't need to change on each machine where the app is deployed
# http://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: en
    cache_type: file_system

framework:
    #esi:             ~
    translator:      { fallbacks: ["%locale%"] }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    #serializer:      { enable_annotations: true }
    templating:
        engines: ['twig']
        #assets_version: SomeVersionScheme
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # handler_id set to null will use default session handler from php.ini
        handler_id:  ~
        save_path:   "%kernel.root_dir%/../var/sessions/%kernel.environment%"
    fragments:       ~
    http_method_override: true
    assets: ~

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"
    number_format:
        thousands_separator: ','
    form_themes:
        - bootstrap_3_layout.html.twig

# Doctrine Configuration
doctrine:
    dbal:
        default_connection:  default
        connections:
            default:
                driver:   pdo_mysql
                host:     "%database_host%"
                port:     "%database_port%"
                dbname:   "%database_name%"
                user:     "%database_user%"
                password: "%database_password%"
                charset:  UTF8
            fulloffice:
                driver:   pdo_mysql
                host:     '127.0.0.1'
#                host:     '178.170.71.223'
                port:     '3306'
                #dbname:   "%database_name%"
                user:     'root'
                password: 'baxe6Equ'
                charset:  UTF8
#        types:
#            datetime: CPA\DoctrineExtensions\DBAL\Types\UTCDateTimeType
                
        
        # if using pdo_sqlite as your database driver:
        #   1. add the path in parameters.yml
        #     e.g. database_path: "%kernel.root_dir%/data/data.db3"
        #   2. Uncomment database_path in parameters.yml.dist
        #   3. Uncomment next line:
        #     path:     "%database_path%"

#    orm:
#        auto_generate_proxy_classes: "%kernel.debug%"
#        naming_strategy: doctrine.orm.naming_strategy.underscore
#        auto_mapping: true
        
    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        default_entity_manager: default
        entity_managers:
            default:
                naming_strategy: doctrine.orm.naming_strategy.underscore
                connection: default
                auto_mapping: true
                mappings:
                    AppBundle:  ~
                    CodeReviewRestBundle:  ~
                    OAuthServerBundle:  ~
                    UserBundle:  ~
                dql:
                    string_functions:
                        MATCH_AGAINST: ourcodeworld\Extensions\Doctrine\MatchAgainst
            fulloffice:
                naming_strategy: doctrine.orm.naming_strategy.underscore
                connection: fulloffice
                mappings:
#                    FrontBundle:  ~
                    UserBundle:  ~
                dql:
                    string_functions:
                        MATCH_AGAINST: ourcodeworld\Extensions\Doctrine\MatchAgainst

doctrine_cache:
    providers:
        my_markdown_cache:
            type: %cache_type%
            file_system:
                directory: %kernel.cache_dir%/markdown_cache
                
#fos_user:
#    db_driver: orm 
#    firewall_name: main
#    user_class: CPA\UserBundle\Entity\User
#    from_email:
#        address: "you@example.com"
#        sender_name: "You"
                
                
#nelmio_api_doc: 
#    routes:
#        path_patterns:
#            - ^/api
#    documentation:
#         info:
#            title: API Intersa
#            description: This is an awesome app!
#            version: 1.0.0



assetic:
    debug:          '%kernel.debug%'
    use_controller: '%kernel.debug%'
    filters:
        cssrewrite: ~
            
nelmio_api_doc:
    name:                 'API documentation'
    exclude_sections:     []
    default_sections_opened:  true
    motd:
        template:             'CPAApiBundle::Default/index.html.twig'
#        template:             'NelmioApiDocBundle::Components/motd.html.twig'
    request_listener:
        enabled:              true
        parameter:            _doc
#    sandbox:
#        enabled:              true
#        endpoint:             null
#        accept_type:          null
#        body_format:
#            formats:
#
#                Defaults:
#                - form
#                - json
#            default_format:       json # ~ One of "form"; "json"
#        request_format:
#            formats:
#
#                # Defaults:
#                json:                application/json
##                xml:                 application/xml
#            method:               accept_header # One of "format_param"; "accept_header"
#            default_format:       json
#        authentication:
#            delivery:             ~ # Required
#            name:                 ~ # Required
#
#            # Required if http delivery is selected.
#            type:                 bearer # ~ One of "basic"; "bearer"
#            custom_endpoint:      false
#        entity_to_choice:         true
    swagger:
        api_base_path:        /api
        swagger_version:      '2.0'
        api_version:          '1.0.0'
        info:
            title:                API Intersa
            description:          'Api RestFull développer avec Symfony3'
            TermsOfServiceUrl:    null
            contact:              null
            license:              null
            licenseUrl:           null
    cache:
        enabled:              false
        file:                 '%kernel.cache_dir%/api-doc.cache'


fos_rest:
    param_fetcher_listener: true
    body_listener: true
    format_listener:
        enabled: true
        rules:
             - { path: ^/api, priorities: [ json ], fallback_format: json, prefer_extension: true }
             - { path: ^/, priorities: [html], fallback_format: html, prefer_extension: true }
             
    view:
        mime_types:
            json: ['application/json', 'application/json;version=1.0', 'application/json;version=1.1']
        view_response_listener: 'force'
        formats:
           json : true 
        templating_formats:
            html: true
        force_redirects:
            html: true
        failed_validation: HTTP_BAD_REQUEST
        default_engine: twig
        
    routing_loader:
#        include_format: false
        default_format: json
    exception:
        codes:
            'Symfony\Component\Routing\Exception\ResourceNotFoundException': 404
            'Doctrine\ORM\OptimisticLockException': HTTP_CONFLICT
        messages:
            'Symfony\Component\Routing\Exception\ResourceNotFoundException': true
    allowed_methods_listener: true
    access_denied_listener:
        json: true
            
    
#    versioning: true
    
    
        
        
fos_oauth_server:
    db_driver:           orm
    client_class:        CPA\OAuthServerBundle\Entity\Client
    access_token_class:  CPA\OAuthServerBundle\Entity\AccessToken
    refresh_token_class: CPA\OAuthServerBundle\Entity\RefreshToken
    auth_code_class:     CPA\OAuthServerBundle\Entity\AuthCode
    authorize:
        form:
            type: fos_oauth_server_authorize
            handler:   fos_oauth_server.authorize.form.handler.default
            name:     fos_oauth_server_authorize_form
            validation_groups:
                - Authorize
                - Default
    service:
        storage:                fos_oauth_server.storage.default
#        user_provider:          fos_user.user_provider 
        user_provider:          platform.user.provider
        client_manager:         fos_oauth_server.client_manager.default
        access_token_manager:   fos_oauth_server.access_token_manager.default
        refresh_token_manager:  fos_oauth_server.refresh_token_manager.default
        auth_code_manager:      fos_oauth_server.auth_code_manager.default
        options:
            supported_scopes: read
#            supported_scopes: string
            access_token_lifetime: 3600
            refresh_token_lifetime: 1209600
            auth_code_lifetime: 3600
#            token_type: string
    template:
        engine:                 twig
