api:
    type:   rest
    resource: "@ApiBundle/Resources/config/routing.yml"
    prefix:   /api



app:
    resource: "@AppBundle/Controller/"
    type:     annotation

#homepage:
#    path: /
#    defaults:
#        _controller: AppBundle:Main:homepage


#fos_user:
#    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

fos_oauth_server_token:
    resource: "@FOSOAuthServerBundle/Resources/config/routing/token.xml"

fos_oauth_server_authorize:
    resource: "@FOSOAuthServerBundle/Resources/config/routing/authorize.xml"
    
    
NelmioApiDocBundle:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix:   /api/doc
    
nelmio_api_swagger:
    resource: "@NelmioApiDocBundle/Resources/config/swagger_routing.yml"
    prefix: /api-docs
    
    
#acme_oauth_server_auth_login:
#    path:     /oauth/v2/auth_login
#    defaults: { _controller: UserBundle:Security:login }
#    
#    
#acme_oauth_server_auth_login_check:
#    path:     /oauth/v2/auth_login_check
#    defaults: { _controller: UserBundle:Security:loginCheck }


user:
    type:   rest
    resource: "@UserBundle/Resources/config/routing.yml"
    prefix:   /



#code_review_rest:
#    type:   rest
#    resource: "@CodeReviewRestBundle/Resources/config/routing.yml"
#    prefix:   /api

o_auth_server:
    resource: "@OAuthServerBundle/Resources/config/routing.yml"
    prefix:   /


