 
api_liste_bulletin:
    path:     /bse
    defaults: { _controller: ApiBundle:Api:listeBulletin }
    
api_download_bulletin:
    path:     /bse/{identifiantBse}
    defaults: { _controller: ApiBundle:Api:downloadBulletin }
