<?php

namespace CPA\OAuthServerBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * CorrespendaceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AuthCodeRepository extends EntityRepository
{
    
    
//    public function findAuthCodeByToken($token){
//        $qb = $this->createQueryBuilder('p')
////                ->select('p.id, p.user, p.token')
//                ->Where('p.token = :token')
//                ->setParameter('token', $token);
//        return $qb->getQuery()
//                ->getArrayResult();
//    }
}