<?php

namespace CPA\UserBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * CorrespendaceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CorrespendanceRepository extends EntityRepository
{
    public function byUserName($username){
        $qb = $this->createQueryBuilder('p')
                ->where('p.username = :username')
                ->setParameter('username', $username);
        return $qb->getQuery()->getResult();
    }
}