<?php

namespace CPA\UserBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * CorrespendaceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SalaryRepository extends EntityRepository
{
    public function byID($id){
        $qb = $this->createQueryBuilder('p')
                ->where('p.id = :id')
                ->setParameter('id', $id);
        return $qb->getQuery()
//                ->getResult();
                ->getArrayResult();
    }
    
    public function findSalarybyUser($user){
        $qb = $this->createQueryBuilder('p')
                ->where('p.user = :user')
                ->setParameter('user', $user);
        return $qb->getQuery()
                ->getArrayResult();
    }
}