<?php

namespace CPA\UserBundle\Repository;

use Symfony\Bridge\Doctrine\Security\User\UserLoaderInterface;
use Doctrine\ORM\EntityRepository;

/**
 * CorrespendaceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends EntityRepository
{
    public function loadUserByUsername($username) {
        return $this->createQueryBuilder('u')
//            ->where('u.username = :username OR u.email = :email')
                        ->where('u.username = :username')
                        ->setParameter('username', $username)
//                        ->setParameter('email', $username)
                        ->getQuery()
                        ->getOneOrNullResult();
    }
    
    public function findbdByUserName($username){
        $qb = $this->createQueryBuilder('p')
                ->where('p.username = :username')
                ->setParameter('username', $username);
        return $qb->getQuery()
                ->getArrayResult();
    }
    public function findUserById($id){
        $qb = $this->createQueryBuilder('p')
                ->where('p.id = :id')
                ->setParameter('id', $id);
        return $qb->getQuery()
//                ->getResult();
                ->getArrayResult();
    }
}